# Numpy Tutorial

In [1]:
import numpy as np

In [2]:
myarr = np.array([[3,4,6,76,67]], np.int32)

In [3]:
myarr[0, 1]

np.int32(4)

In [4]:
myarr.shape

(1, 5)

In [5]:
myarr.dtype

dtype('int32')

 **Array creation: Conversion from other Python structures**

In [6]:
listarray = np.array([[1,2,3], [5,8,5],[0,3,1]])

In [7]:
listarray

array([[1, 2, 3],
       [5, 8, 5],
       [0, 3, 1]])

In [8]:
listarray.dtype

dtype('int64')

In [9]:
listarray.shape

(3, 3)

In [10]:
listarray.size

9

In [11]:
np.array([34,54,56])

array([34, 54, 56])

In [12]:
zeros = np.zeros((2,4))

In [13]:
zeros.shape

(2, 4)

In [14]:
zeros.size

8

In [15]:
rng = np.arange(15)

In [16]:
rng

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [17]:
ispace = np.linspace(1,4,4)

In [18]:
ispace

array([1., 2., 3., 4.])

In [19]:
emp = np.empty((4,6))

In [20]:
emp

array([[6.23042070e-307, 4.67296746e-307, 1.69121096e-306,
        6.23047842e-307, 2.22526399e-307, 6.23053614e-307],
       [1.29060871e-306, 6.23055651e-307, 1.06811422e-306,
        3.56043054e-307, 1.37961641e-306, 1.05695167e-307],
       [1.78020169e-306, 7.56601165e-307, 1.02359984e-306,
        1.33510679e-306, 2.22522597e-306, 8.01097889e-307],
       [1.06811354e-306, 6.89807188e-307, 9.34609111e-307,
        1.42419530e-306, 2.22522596e-306, 3.91786943e-317]])

In [21]:
emp_like = np.empty_like(ispace)

In [22]:
emp_like

array([1., 2., 3., 4.])

In [23]:
ide = np.identity(45)

In [24]:
ide

array([[1., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 0., 1.]], shape=(45, 45))

In [25]:
ide.shape

(45, 45)

In [26]:
ide.size

2025

In [27]:
arr = np.arange(99)

In [28]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [29]:
arr = arr.reshape(3,33)

In [30]:
arr

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32],
       [33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,
        49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64,
        65],
       [66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
        82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97,
        98]])

In [31]:
arr = arr.ravel()

In [32]:
arr.shape

(99,)

**NUMPY AXIS**

In [33]:
x = [[1,2,3], [4,5,6],[7,8,9]]

In [34]:
ar = np.array(x)

In [35]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [36]:
ar.sum(axis = 0)

array([12, 15, 18])

In [37]:
ar.sum(axis = 1)

array([ 6, 15, 24])

In [38]:
ar.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [39]:
ar.flat

In [40]:
for item in ar.flat:
    print(item)

1
2
3
4
5
6
7
8
9


In [41]:
ar.ndim

2

In [42]:
ar.size

9

In [43]:
ar.dtype

dtype('int64')

In [44]:
ar.nbytes

72

In [45]:
one = np.array([1,3,4,543,2])

In [46]:
one.argmax()

np.int64(3)

In [47]:
one.argmin()

np.int64(0)

In [48]:
one.argsort()

array([0, 4, 1, 2, 3])

In [49]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [50]:
ar.argsort()

array([[0, 1, 2],
       [0, 1, 2],
       [0, 1, 2]])

In [51]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [52]:
ar.argmin()

np.int64(0)

In [53]:
ar.argmax(axis = 0)

array([2, 2, 2])

In [54]:
ar.argmin(axis = 0)

array([0, 0, 0])

In [55]:
ar.argmax(axis = 1)

array([2, 2, 2])

In [56]:
ar.argsort(axis = 0)

array([[0, 0, 0],
       [1, 1, 1],
       [2, 2, 2]])

In [57]:
ar.argsort(axis = 1)

array([[0, 1, 2],
       [0, 1, 2],
       [0, 1, 2]])

In [58]:
ar.ravel()

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [59]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [60]:
ar2 = np.array([[1,2,3],
                [4,5,6],
                [8,1,0]])

In [61]:
ar2

array([[1, 2, 3],
       [4, 5, 6],
       [8, 1, 0]])

In [62]:
ar + ar2

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [15,  9,  9]])

In [63]:
[12,3] + [4,7]

[12, 3, 4, 7]

In [64]:
ar*ar2

array([[ 1,  4,  9],
       [16, 25, 36],
       [56,  8,  0]])

In [65]:
np.sqrt(ar)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974],
       [2.64575131, 2.82842712, 3.        ]])

In [66]:
ar*ar

array([[ 1,  4,  9],
       [16, 25, 36],
       [49, 64, 81]])

In [67]:
ar.sum()

np.int64(45)

In [68]:
ar.max()

np.int64(9)

In [69]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [70]:
np.where(ar>5)

(array([1, 2, 2, 2]), array([2, 0, 1, 2]))

In [71]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [72]:
type(np.where(ar>6))

tuple

In [73]:
np.count_nonzero(ar)

np.int64(9)

In [74]:
np.nonzero(ar)

(array([0, 0, 0, 1, 1, 1, 2, 2, 2]), array([0, 1, 2, 0, 1, 2, 0, 1, 2]))

In [75]:
import sys

In [76]:
py_ar = [23,4,56,6]

In [77]:
np_ar = np.array(py_ar)

In [78]:
sys.getsizeof(1) * len(py_ar)

112

In [79]:
np_ar.itemsize * np_ar.size

32